name: cryolens
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ase
  - numpy<2
  - pillow
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - ipykernel
  - fastapi
  - pip
  - pip:
      - pathos
      - copick
      - gemmi
      - dscribe
      - torch
      - pytorch-lightning
      - torchvision